# Generated by Django 4.2.1 on 2023-05-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0003_privacypolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политики конфиденциальности'},
        ),
    ]
