# Generated by Django 4.2.1 on 2023-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0004_alter_privacypolicy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.IntegerField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
