# Generated by Django 4.2.1 on 2023-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0005_product_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
