# Generated by Django 4.2.1 on 2023-05-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0006_alter_product_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autoshop.cart', verbose_name='Корзина'),
        ),
    ]
